### ISSUE TITLE
Cannot find module './build/Release/shell' due to execSync dependency in doppio

### ISSUE THREAD

**Issue by jimfb** [jvilk/doppio-demo#13]
Running "grunt build" will sometimes result in:

```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module './build/Release/shell'
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
```

I believe the error is related to execSync which is a dependency of this project.  The version that gets installed apparently doesn't build on some versions of npm/node.  Root cause is related to: https://github.com/mgutz/execSync/issues/27 though I do have python 2.7.

My solution was to use `nvm` to downgrade my npm/node install to v0.10.30, which worked for me.  While probing for a good npm/node version, I noticed that v0.10.0 does not work (too low), so the acceptable version dependency range is somewhat narrow.

I'm posting this issue here mostly so that when someone does a google/github/doppio search for the error, they will find this and my notes will be helpful in some way, but it's worth tracking the issue and trying to expand the acceptable dependency version range (particularly in the up direction).

**Comment by jvilk** [comment]
Thanks for the report! I'm actually working on fixing this myself.

**Comment by jvilk** [comment]
And I'm planning to remove the dependency on `execSync` in the next version of this project, as that functionality is in Node v0.12.
