### ISSUE TITLE
build: grunt's `javac:default` task fails on fresh doppio-demo checkout

### ISSUE THREAD

**Issue by bpowers** [jvilk/doppio-demo#16]
I'm trying to build the demo, and seeing this:

```
02:17:11 (master) [bpowers@aika doppio-demo]$ grunt
Recompiling /home/bpowers/plasma/doppio-demo/tasks/find_native_java.ts...
Recompiling /home/bpowers/plasma/doppio-demo/tasks/java.ts...
Recompiling /home/bpowers/plasma/doppio-demo/tasks/listings.ts...
Recompiling /home/bpowers/plasma/doppio-demo/Grunttasks.ts...
Running "find_native_java" task
Locating JDK8 installation...
>> Using JDK8 installation at /usr/lib/jvm/oracle-jdk-bin-1.8
>> Java: /usr/lib/jvm/oracle-jdk-bin-1.8/bin/java
>> Javap: /usr/lib/jvm/oracle-jdk-bin-1.8/bin/javap
>> Javac: /usr/lib/jvm/oracle-jdk-bin-1.8/bin/javac

Running "javac:default" (javac) task
Fatal error: Error running javac: Error: Command failed: /usr/lib/jvm/oracle-jdk-bin-1.8/bin/javac -J-Dfile.encoding=UTF8 -bootclasspath undefined -source 1.8 -target 1.8 demo_files/classes/demo/Chatterbot.java demo_files/classes/demo/Diff.java demo_files/classes/demo/DiffPrint.java demo_files/classes/demo/Fib.java demo_files/classes/demo/GzipDemo.java demo_files/classes/demo/RegexTestHarness.java demo_files/classes/doppio/Debug.java demo_files/classes/doppio/JavaScript.java demo_files/classes/util/FindJclClasses.java demo_files/classes/util/Javac.java demo_files/classes/util/Javap.java demo_files/classes/util/SystemProperties.java demo_files/classes/util/Unzip.java
Fatal Error: Unable to find package java.lang in classpath or bootclasspath
```

Notice the `-bootclasspath undefined`.  In [`java.ts`](https://github.com/jvilk/doppio-demo/blob/14d83d6/tasks/java.ts#L36) this is loaded from the config:

```
let bootclasspath = grunt.config('build.bootclasspath');
```

But I don't see it actually set from anywhere?

**Comment by jvilk** [comment]
Good catch. We should populate it via the JSON in our `java_home` directory like I do in Doppio's Grunt file.

**Comment by amahdy** [comment]
One workaround to get rid of this error is to add after the following line https://github.com/jvilk/doppio-demo/blob/14d83d6de3696d3f388893c29e9bc9ffce395540/tasks/find_native_java.ts#L22

This:

```ts
grunt.config.set('build.bootclasspath', home.path + "/jre/lib/rt.jar:" + home.path + "lib/tools.jar");
```

But most probably this won't fix the build for good. Basically this demo appear to be build with `doppiojvm 0.4.?` so you should not clone the `master` nor version `0.5.0`.

I can make a PR if needed.

**Comment by jvilk** [comment]
I'll accept a PR, but you'll need to use `path.join` and [replace `:` with `;` on Windows](https://github.com/jvilk/doppio-demo/blob/master/tasks/java.ts#L38) so this also works on Windows.

I believe this demo should work with the `master` branch. The instructions in the README instruct you to use a `link`ed Doppio, which can be a stable version or the `master` branch. If you encounter problems, feel free to file issues / submit PRs.

**Comment by amahdy** [comment]
PR created. Switched the place of checking for the paths separator since `bootclasspath` is now guaranteed to be correct.

Based on my tests, it does not work with `0.5.0`, I think the main problem is conflicts of the `browserfs` library. Here it's using `0.5.11` but `doppio 0.5.0` uses `^1.0.0`. Works fine with `doppio 0.4.2`.

**Comment by amahdy** [comment]
You were also using coffee script here, this causes many conflicts in grunt tasks.
