### ISSUE TITLE
demo fails during JVM init

### ISSUE THREAD

**Issue by perimosocordiae** [jvilk/doppio-demo#6]
When you try to run a java program, the demo fails with:

```
Uncaught TypeError: Cannot read property 'throwNewException' of null  doppio.js:4
t.throwClassNotFoundException  doppio.js:4
```

Looks like we try to load the `java/lang/Thread` class during the bootstrap initialization (where we use a null thread object), but the `_loadClass` method fails. We try to throw an exception, but there's no thread to throw it on.

**Comment by jvilk** [comment]
Right! I didn't put in the logic to copy over the JCL yet to the build folder, because I want to re-JAR the JARs.

**Comment by perimosocordiae** [comment]
Ah, makes sense. The `bootstrapClasspath` contains only `classes.jar`, which I assume we don't know how to handle yet.

**Comment by jvilk** [comment]
Yeah. Although as-discussed, I'm going to recompress the core JAR files in the JDK, preload them w/ a nice progress bar, and plop them on the bootstrap classpath.

I might also hack in caching into the zipfs. If I have time.

**Comment by jvilk** [comment]
fixd
