### ISSUE TITLE
Huge performance regression

### ISSUE THREAD

**Issue by jvilk** [jvilk/doppio-demo#8]
Javap, for example, is 40X+ slower.

Not sure if it's the unzipping or something else, but we can't ship a new demo until this is addressed.

**Comment by perimosocordiae** [comment]
It's likely the unzipping. We may need to hold off on the jar magic until we excise jazzlib from Doppio.

**Comment by perimosocordiae** [comment]
Does this mean you fixed issue #6 ? It's still busted on my end.

**Comment by jvilk** [comment]
I did. Delete `/vendor/java_home`, and your build directory, and rebuild. It'll grab an experimental new java_home.
